package com.example.eCommerce.service.product;

import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.UUID;

@Service
public class FileServiceImpl implements FileService {

    @Override
    public String uploadImage(String path, MultipartFile image) throws IOException {
        // Get the file name of original file
        /**
         * So getName is the method that provide the original file name and it never null. It is a method in the Multipart
         * file.
         */
        String originalFilename = image.getOriginalFilename();
        // Generate a unique file name
        String randomId = UUID.randomUUID().toString();
        // if original file name is Math.jpg so we are changing to 1234.jpg that number is generated by uuid
        String fileName = randomId.concat(originalFilename.substring(originalFilename.lastIndexOf(".")));
        String filePath = path + File.separator + fileName;
        // check if path exist if not then create
        File folder = new File(path);
        if (!folder.exists()) {
            folder.mkdirs();
        }
        // upload to server
        Files.copy(image.getInputStream(), Paths.get(filePath));
        // return file name
        return fileName;


    }

}
